### ISSUE TITLE
MacOs Support High Sierra 10.13.6

### ISSUE THREAD

**Issue by tomsmile0** [rileytestut/AltStore#107] opened 2020-02-14 17:37 UTC
Can someone help me run MacOs High Sierra 10.13.6?

**Comment by BartmanEH** [comment] 2020-02-14 22:12
duplicate of [https://github.com/rileytestut/AltStore/issues/88#issue-549952273](https://github.com/rileytestut/AltStore/issues/88#issue-549952273)

**Comment by noah978** [comment] 2020-05-22 04:58
Closing since this is a duplicate of #88.

**Closed by noah978** 2020-05-22 04:58 UTC
Labels: duplicate
