### ISSUE TITLE
[Idea] Support for multiple iCloud accounts

### ISSUE THREAD

**Issue by Bright-Shard** [rileytestut/AltStore#723] opened 2021-03-24 00:02 UTC
One of the main limiting features of AltStore (For free developer accounts) is that you can only install so many apps, and you can only sign so many apps per week. This is why adding support for multiple iCloud accounts could be helpful; when you first setup AltStore, you use your main one, but then (in settings) you could add a second or third account, thus increasing the app limit (obviously there might should be some limit to this so people aren't making hundreds of iCloud accounts.) This way, when one account is maxed out of apps, AltStore could switch to the next account to install more apps.

**Comment by binyaminyblatt** [comment] 2021-11-04 13:28
Please add this feature

**Comment by JJTech0130** [comment] 2022-05-09 19:18
Duplicate of https://github.com/rileytestut/AltStore/issues/579

**Closed** 2023-01-11 22:50 UTC
