### ISSUE TITLE
AltStore isn't opening

### ISSUE THREAD

**Issue by aa1201** [rileytestut/AltStore#656] opened 2021-01-30 10:53 UTC
I forgot to refresh my altstore app on my iphone. I reinstalled it from my pc but when I open the app it closes suddenly and I can't do anything.

**Comment by filippogrande** [comment] 2021-01-30 14:14
I have the same problem 

Uploading IMG_0202.MP4…

**Comment by filippogrande** [comment] 2021-01-30 14:20
I have the identical problem

https://user-images.githubusercontent.com/35425860/106358798-ac84ac00-630e-11eb-9847-598450fcbc6f.MP4

**Comment by Tony-Sol** [comment] 2021-01-30 18:33
same

**Comment by GiovanH** [comment] 2021-01-30 21:17
Duplicate of https://github.com/rileytestut/AltStore/issues/652

**Comment by shanegillio** [comment] 2023-01-13 17:51
closing because of duplicate

**Closed by shanegillio** 2023-01-13 17:51 UTC
