### ISSUE TITLE
Is it possible to install clones of altstore ? (multiple apple IDs)

### ISSUE THREAD

**Issue by masckmaster2007** [rileytestut/AltStore#999] opened 2022-05-07 10:18 UTC
I want to use many apps, but i am limited to 3 apps. Is it 3 apps per device or 3 apps per account ? 
If it is per account, is it possible to install altstore, but with another Apple ID ?

**Comment by JJTech0130** [comment] 2022-05-09 19:19
Duplicate of #723 and #579

**Closed** 2022-05-22 11:57 UTC
