### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by alyyy4600** [rileytestut/AltStore#223] opened 2020-05-26 13:22 UTC
![94C47F71-8C52-45C2-A9FF-0530D59D491E](https://user-images.githubusercontent.com/65959953/82905875-07952080-9f82-11ea-937a-d2672b176971.jpeg)

**Comment by noah978** [comment] 2020-05-27 05:21
Duplicate of #205. Closing.

**Closed by noah978** 2020-05-27 05:21 UTC
Labels: duplicate

**Comment by alyyy4600** [comment] 2020-05-27 07:06
I didn't get it ???
