### ISSUE TITLE
Altstore app crashes 

### ISSUE THREAD

**Issue by ragga2** [rileytestut/AltStore#655] opened 2021-01-30 10:04 UTC
Hi,
Im using iphone11 pro (jail broken - iOs 13.5.) and have been using altstore for over an year but this time around when i re-installed it - it keeps crashing on my iphone. 

I have tried various permutation and combinations like updating altstore to 1.4.1, updating icloud and updating itunes as well. 

i also tried sideloading **uncover** via 3uTools as well but it also doesnt upon on my iphone post successful downloading.

Please help me out as i dont wont to upgrade to iOs14.

Thank you

**Comment by reubn** [comment] 2021-01-30 10:25
There's a very easy way to fix this, until the update's released. Take the [new `apple.pem` file](https://raw.githubusercontent.com/rileytestut/AltSign/8ce86befc8621c290ef916f8694a0ffc3cd99f14/AltSign/Resources/apple.pem), and replace the old one in `AltServer.app`: `AltServer.app/Contents/Resources/AltSign_CAltSign.bundle/Contents/Resources/apple.pem`.
Restart AltServer.

Just resigned all my apps with no trouble.

**Comment by ragga2** [comment] 2021-01-30 16:51
didnt work for me. I downloaded the "apple.pem" file from the above link and replace the same with the same file in the altstore folder on my windows laptop. Restarted my computer and re-installed altserver on my iphone and it still crashes.

Please suggest

**Comment by reubn** [comment] 2021-01-30 16:54
> didnt work for me. I downloaded the "apple.pem" file from the above link and replace the same with the same file in the altstore folder on my windows laptop. Restarted my computer and re-installed altserver on my iphone and it still crashes.
> 
> Please suggest

No idea, seems to have worked for me and a few others, while other's haven't had such success. Suspect there are other issues at play - stopping it from working for you

**Comment by ragga2** [comment] 2021-01-30 16:56
Did i follow the right steps?
Any other thing i could do.

**Comment by reubn** [comment] 2021-01-30 17:15
[This](https://we.tl/t-gfAbxkPpLw) is my modified copy of `AltServer.app`, see if it works

**Comment by ragga2** [comment] 2021-01-30 17:44
im using a windows machine.

**Comment by reubn** [comment] 2021-01-30 17:46
Ah shit yeah. Can't really help much more then. I suspect you're not downloading/copying the file intact somehow.

**Comment by ragga2** [comment] 2021-01-30 17:58
let me give it a try again.

**Comment by ragga2** [comment] 2021-01-30 18:28
didnt work. feeling helpless...:( :(

**Comment by GiovanH** [comment] 2021-01-30 21:18
Duplicate of https://github.com/rileytestut/AltStore/issues/652

**Comment by affanblaze** [comment] 2021-01-31 13:56
Ragga same problem, although i have iphone xr

**Comment by shanegillio** [comment] 2023-01-13 17:51
closing because of duplicate

**Closed by shanegillio** 2023-01-13 17:51 UTC
