### ISSUE TITLE
Altstore crashing while sideloading large ipa files.

### ISSUE THREAD

**Issue by MaverickF14A** [rileytestut/AltStore#307] opened 2020-07-30 17:00 UTC
**Describe the bug**
Whenever I try to side load large ipa files, the green bar loads up to around 75% and then AltStore crashes and when you open it again, there is no app but the app ID is signed. So, the app is not installed. The same thing happens no matter how many times you try, with different devices /Apple ids etc. 

**To Reproduce**
1. Try to side load a large ipa file over 1gb/500mb size, in my case is a file which is around 2.5GB and then see the error.

**Expected behavior**
Altstore will close and you will return to the home screen. And when you open it again, there will be no app but an app Id will be present.

**Screenshots**
![ADF5290F-2EA8-4674-A40A-75CD4152B6B6](https://user-images.githubusercontent.com/68789929/88951595-d69fd780-d2b3-11ea-9b39-563667db1249.png)

**Desktop (please complete the following information if applicable):**
 - OS: [Windows]
 - Version[10]

**iPhone (please complete the following information):**
 - Device: [iPhone6s] and [IPad Pro 2017 9.7 inches]
 - iOS: [e.g. 13.5.1]

**Additional context and logs**
The app ID appears and takes up space as one of the 10.

**Comment by jackstewert** [comment] 2020-07-30 17:04
Same here

**Comment by DavideBri** [comment] 2020-08-03 18:53
**same**

**Comment by noah978** [comment] 2021-01-05 17:54
Duplicate of #303

**Closed by noah978** 2021-01-05 17:54 UTC
Labels: bug
