### ISSUE TITLE
Unable to Download Apps. "Failed to write app data to device." 

### ISSUE THREAD

**Issue by Joshuarox100** [rileytestut/AltStore#40] opened 2019-10-04 21:41 UTC
iPhone XR running iOS 13.1.2.
I installed the AltServer on my Win 10 PC and installed AltStore to the phone successfully, but upon trying to download either Delta or its Lite counterpart, the progress bar shown when downloading nearly completes, halts, and shortly after throws the error, "Failed to write app data to device." I don't know to really troubleshoot this issue, given that it is not mentioned in the FAQ page.

**Comment by MacularDegenerate** [comment] 2019-10-14 12:31
I have the exact same software/hardware setup.  I was able to initially install AltStore and Delta to my phone, but I get this error message when trying to Refresh either app.  The progress bar gets just beyond halfway then throws this error every time.  Occasionally I also get "AltServer could not find this device." despite AltServer running with both my phone and PC on the same network. I would be interested to know if anyone finds a solution.

**Comment by MacularDegenerate** [comment] 2019-10-14 12:55
Update: Delta and AltStore seem to Refresh without issues if the phone is plugged into my PC, but still no luck Refreshing over WiFi. Plugging in seems to be a temporary fix, but I would still like to be able to update over WiFi so AltStore can handle periodic Refreshes in the background as intended.

**Comment by anastarawneh** [comment] 2019-12-22 17:51
Yup, same problem. A few days ago it worked fine, updating my apps in the background automatically, but now it's back to this. Have you guys found some way to fix this?

**Comment by Joshuarox100** [comment] 2019-12-22 20:01
I've found a workaround that seems to not be a problem with Altstore but with iTunes. So after every PC boot, I need to restart the Apple Mobile Device Service in task manager before iTunes or Altstore detect my phone on the network. I don't know why this is the case, but it does temporarily fix the problem for me until I restart my computer, in which case I just restart the service again.
![image](https://user-images.githubusercontent.com/12418573/71326660-83ff7100-24c3-11ea-9066-4e66b4fcdffb.png)

**Comment by P8Kcv6n** [comment] 2020-01-07 23:34
That service is needed to detect and communicate with iDevices, so the solution for now would be to create a small script to check if it's running, and if it isn't start it. Then set a scheduled task to run the script once a day or so.

**Comment by Umarovm** [comment] 2020-04-20 16:54
I have this same issue but when sideloading an iPA from Files. It installs when I use AltDeploy but not AltStore. I want to install it with AltStore because whenever I install it with AltDeploy, I can't refresh it. Except I have a Mac and an iPhone XR on iOS 12.4.1.

**Comment by noah978** [comment] 2020-05-22 02:25
The randomly stopping Apple Mobile Device Service on windows is something that will hopefully get addressed in the future. For now, you might find something [AltCheck](https://github.com/DiscordDigital/AltCheck) useful.

**Comment by noah978** [comment] 2020-05-22 02:25
@Umarovm What IPA are you having issues installing and what is the exact error AltStore gives you?

**Comment by Umarovm** [comment] 2020-05-22 02:53
I tried to install Mini vMac: https://github.com/zydeco/minivmac4ios
I might have done it wrong but I made the iPA by compiling it with Xcode and made an Xcode Archive (.xcarchive) of it and then right clicked on it and clicked "Show Package Contents", then I went to Products/Applications and I followed [this](https://stackoverflow.com/questions/1191989/create-ipa-for-iphone) to make an iPA of it. [This is what I resulted with.](https://github.com/Umarovm/-/raw/master/Mini%20vMac.ipa) And I assumed it worked because AltDeploy worked with it. When I tried another way to make an iPA file by going to Product -> Archive -> Distribute App -> Ad Hoc, it says I have to be in the Apple Developer Program, which I'm not willing to pay for. Is there anyway to make this into an iPA (if I did it wrong) so that AltStore can install it?

**Comment by noah978** [comment] 2020-05-22 03:38
It seems to be just an issue with the IPA. Interestingly, I get "could not find matching provisioning profile" using the latest AltStore Alpha build. Not sure if it can handle the VMs you are trying to get running but I would recommend [UTM](https://github.com/utmapp/UTM) as probably the best VM manager for iOS.

**Closed** 2020-05-22 04:07 UTC
