### ISSUE TITLE
AltServer for Linux

### ISSUE THREAD

**Issue by SchoolBusesC2** [rileytestut/AltStore#221] opened 2020-05-26 00:44 UTC
Hello,

Could you guys develop AltServer for Linux?

Thanks,
Owen

**Comment by Terrain2** [comment] 2020-05-26 01:19
Apple doesn't distribute iTunes for linux, so almost certainly not

Don't get me wrong, it's not impossible, in fact, [Cydia Impactor has a Linux version](https://cydia.saurik.com/api/latest/4), and tools like [iSign](https://github.com/sauce-archives/isign) can do this, but AltStore currently uses only the official apple tools provided for Mac and Windows because they're reliable

It's probably not gonna happen anytime soon, maybe try a Windows VM?

**Comment by Terrain2** [comment] 2020-05-26 01:39
Also, duplicate of #6

**Closed** 2020-05-29 19:04 UTC
Labels: enhancement
