### ISSUE TITLE
Mail Plug-in Broken on Big Sur Beta 2

### ISSUE THREAD

**Issue by Lester702** [rileytestut/AltStore#299] opened 2020-07-20 23:35 UTC
**Describe the bug**
Mail throws a fit when enabling the plug-in on macOS Big Sur

**To Reproduce**
1. Upgrade to Big Sur
2. Install mail plug-in
3. Try to enable it

**Expected behavior**
The mail plug-in loads normally

**Screenshots**
![image](https://user-images.githubusercontent.com/63370028/87996428-20244180-cac0-11ea-98c2-f38090559525.png)

**Desktop (please complete the following information if applicable):**
Mac
Big Sur Beta 2

**iPhone (please complete the following information):**
iPhone 11 on 13.5

**Additional context and logs**
Add any error logs or any other context about the problem here.

**Comment by Lester702** [comment] 2020-07-20 23:36
Just saw #289.

**Comment by noah978** [comment] 2020-08-23 19:27
Duplicate of #278 .

**Closed by noah978** 2020-08-23 19:27 UTC
Labels: bug
