### ISSUE TITLE
Installation Failed Invalid anisette data Please close both itunes and icloud and try again

### ISSUE THREAD

**Issue by Alphaltz** [rileytestut/AltStore#208] opened 2020-05-24 17:13 UTC
Shows this but itunes and icloud are closed 
![image](https://user-images.githubusercontent.com/61337318/82760248-bd1c7400-9dc8-11ea-86a5-249416d23032.png)

**Comment by noah978** [comment] 2020-05-24 17:36
Duplicate of #156.

**Closed by noah978** 2020-05-24 17:36 UTC
Labels: duplicate

**Comment by Alphaltz** [comment] 2020-05-25 19:43
It isnt a duplicate it is different issue.
