### ISSUE TITLE
Support for Linux in the future?

### ISSUE THREAD

**Issue by ghost** [rileytestut/AltStore#111] opened 2020-02-17 23:13 UTC
In the future can this be ran on Linux Ubuntu Arch etc?

**Comment by realmayus** [comment] 2020-02-21 11:30
Did you try using Wine?

**Comment by Austcool-Walker** [comment] 2020-02-23 13:31
> Did you try using Wine?

no but I'll try and get back with you.

**Comment by Austcool-Walker** [comment] 2020-02-23 14:45
@realmayus I tried it isn't working because of I could required programs that I couldn't get in wine... A native build against libimobiledevice would be best I think.

**Comment by BananaManCJ** [comment] 2020-04-17 02:55
I highly doubt we'll ever get a native AltServer for Linux since the Apple Mobile Device driver doesn't exist for Linux

**Comment by noah978** [comment] 2020-05-22 22:26
Duplicate of #6. Closing this issue.

**Closed by noah978** 2020-05-22 22:26 UTC
Labels: duplicate
