### ISSUE TITLE
Altstore not installing on phone

### ISSUE THREAD

**Issue by smellslikegithub** [rileytestut/AltStore#213] opened 2020-05-24 19:23 UTC
**Describe the bug**
Trying to install altstore, using altserver but getting this error every time.

**To Reproduce**
1. Install altserver
2. Install Altstore
3. provide username and password

**Expected behavior**
Altstore should be installed on iphone

**Screenshots**
![image](https://user-images.githubusercontent.com/11131381/82762969-6d5b9e00-9e04-11ea-820d-7f392b499d1b.png)

**Desktop (please complete the following information if applicable):**
 - Windows 10, 64bit, Version 1903, OS-Build: 18362.836

**iPhone (please complete the following information):**
 - Device: [iPhone 6s Plus]
 - iOS: [13.5]

**Comment by noah978** [comment] 2020-05-24 21:09
Duplicate of #94. You can find the solution there.

**Closed by noah978** 2020-05-24 21:09 UTC
Labels: duplicate
