### ISSUE TITLE
error -22411 on mac big sur

### ISSUE THREAD

**Issue by itschews** [rileytestut/AltStore#318] opened 2020-08-06 09:58 UTC
basically it says that when i use a different acc, I have 3 accounts 1 to use for icloud on my devices and 2 other alts which I accepted the dev agreement on 1 alt acc works but the other doesn't idk why

 I made a new acc it didn't work either

**Comment by noah978** [comment] 2020-08-23 19:16
Duplicate of #278. You need a special version of AltServer to work on Big Sur.

**Closed by noah978** 2020-08-23 19:16 UTC
Labels: bug
