### ISSUE TITLE
Feature Request: Altserver for Linux.

### ISSUE THREAD

**Issue by Spidy123222** [rileytestut/AltStore#433] opened 2020-11-13 08:25 UTC
There has been program that have been used on Linux to sign apps especially recently like Zsign wich is on Linux. I don't know if this of any use but I thought this would be a nice way to sign apps. Using like ISH or on a small Linux server you can carry around and can sign with hotspot on. 
Zsign Github: https://github.com/zhlynn/zsign

**Comment by JoelOsler** [comment] 2020-11-14 20:58
AltServer in iSH would be absolutely epic!

**Comment by chrissxYT** [comment] 2020-11-18 23:34
Have been wanting this for a long time, porting a macOS daemon to Linux/other Unixes shouldn’t be a big problem.

**Comment by Spidy123222** [comment] 2020-11-19 02:36
> Have been wanting this for a long time, porting a macOS daemon to Linux/other Unixes shouldn’t be a big problem.

Yes I hope that the GitHub link I use will help. I haven't coded so this can't be a PR so it's here.

**Comment by christopherbaxley** [comment] 2020-11-19 10:29
@Spidy123222 AltServer doesn't really perform the signing, its primary job is installing and refreshing what is on the device via iTunes WiFi Sync.

With that in mind, digging through the implementation of AltServer, it looks to heavily depend on libimobiledevice to handle communication with iOS devices in ALTDeviceManager. This library does natively support GNU/Linux, including WiFi Sync features on which AltServer requires. Given the recent port of Swift Core to GNU/Linux, AltServer's transition from CocoaPod to Swift and the cross-platform nature of this library, it seems feasible at first glance. 

Don't get your hopes too high yet. AltServer's Windows port requires iTunes and iCloud to be installed. As the documentation in libimobiledevice requires digging through each file, I haven't had the time yet to determine if there are specific library functions that depend on iTunes or not, let alone finding them in AltServer itself.

If @rileytestut could confirm which parts of AltServer interact with iTunes, I would be happy to lend some time to this effort. If iTunes is a strict requirement that cannot be worked around, that will impede such a port. Though I am not myself a Swift developer (primarily Python at the moment), the best way to learn is by doing.

**Comment by Spidy123222** [comment] 2020-11-25 20:52
> @Spidy123222 AltServer doesn't really perform the signing, its primary job is installing and refreshing what is on the device via iTunes WiFi Sync.
> 
> 
> 
> With that in mind, digging through the implementation of AltServer, it looks to heavily depend on libimobiledevice to handle communication with iOS devices in ALTDeviceManager. This library does natively support GNU/Linux, including WiFi Sync features on which AltServer requires. Given the recent port of Swift Core to GNU/Linux, AltServer's transition from CocoaPod to Swift and the cross-platform nature of this library, it seems feasible at first glance. 
> 
> 
> 
> Don't get your hopes too high yet. AltServer's Windows port requires iTunes and iCloud to be installed. As the documentation in libimobiledevice requires digging through each file, I haven't had the time yet to determine if there are specific library functions that depend on iTunes or not, let alone finding them in AltServer itself.
> 
> 
> 
> If @rileytestut could confirm which parts of AltServer interact with iTunes, I would be happy to lend some time to this effort. If iTunes is a strict requirement that cannot be worked around, that will impede such a port. Though I am not myself a Swift developer (primarily Python at the moment), the best way to learn is by doing.

Yeah I knew Altserver utilizes Libimobiledevice wich kind of made me think Linux is possible and obviously other programs can run on Linux that are similar and idk they use libimobiledevice but they probobly do. If making Altserver on Linux it would make it possible in theory to not need iTunes or iCloud imo. I only do luau scripting so I won't be too much help.

**Comment by noah978** [comment] 2021-01-05 18:17
Duplicate of #6

**Closed by noah978** 2021-01-05 18:17 UTC
