### ISSUE TITLE
Kodi not installing

### ISSUE THREAD

**Issue by MillenniumAlpha** [rileytestut/AltStore#232] opened 2020-05-29 20:26 UTC
**I was installing Kodi on my iPhone 7 and Kodi successfully installs but the app doesn't appear on the home screen and neither does a profile, also Kodi doesn't appear in the my apps bit in AltStore**

**To Reproduce**
1. Go to https://kodiipa.com/ and download the .ipa file.
2. Install the .ipa file like you would through AltServer and AltStore.
3. Wait for it to install

**Expected behavior**
I expected that the .ipa would install correctly and show up on the home screen of my device

**Screenshots**
https://imgur.com/a/io1ljwK

 - OS: Windows 10 Home 64-bit
 - Version: 1909

**iPhone (please complete the following information):**
 - Device: iPhone 7
 - iOS: 13.5

**Comment by noah978** [comment] 2020-05-31 03:35
Duplicate of #162. But thanks for providing lots of info.

**Closed by noah978** 2020-05-31 03:35 UTC
Labels: duplicate
