### ISSUE TITLE
issue with the newest version on windows 10

### ISSUE THREAD

**Issue by imnisp** [rileytestut/AltStore#224] opened 2020-05-26 15:54 UTC
the procedure entry point IsWow64Process2 could not be located

**Comment by jack980517** [comment] 2020-05-27 01:26
I'm having this problem as well, and according to [a Reddit thread](https://www.reddit.com/r/AltStore/comments/gpjd9u/dll_error_after_updating_altstore/), downgrading to 1.3.1 beta 1 fixes it.

**Comment by noah978** [comment] 2020-05-27 05:22
Duplicate of #205. Closing.

**Closed by noah978** 2020-05-27 05:23 UTC
Labels: duplicate
