### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by cdK1337** [rileytestut/AltStore#210] opened 2020-05-24 17:53 UTC
Trying to install Altstore, but it gives me an error: "Failed to verify code signature of /private/var/installd'Library/Caches/com.apple.mobile.installd,staging/temp.4TdWwd/extracted/Altstore.app : 0xe800800d (There was an error communicating with your device.)"
I'm using Win7. About 2 months ago it worked pefrectly for me, but now I can't install it. Trying to install it on iPhone 5S iOS 12.4. iTunes and icloud installed. Screenshot attached.
![bugorsmth](https://user-images.githubusercontent.com/65866326/82761075-84988c80-9e00-11ea-9b3c-a9e116366dcb.jpg)

**Comment by cdK1337** [comment] 2020-05-24 20:40
Probably, that something wrong with my iPhone. I tried to install Altstore to my new SE and it works perfectly. Trying to install to 5S and receive error message. Also installed virtual machine for last version Altserver, it didn't helped me, still can't install it on 5S. Probably, wipe all data on iDevice will help me, but will try to solve this problem.

**Comment by noah978** [comment] 2020-05-24 21:08
Duplicate of #94. You can find the solution there.

**Closed by noah978** 2020-05-24 21:08 UTC
Labels: duplicate
