### ISSUE TITLE
(question) error xxx11 (don't remember the number exactly) happened when I tried installing altstore on my iPad 2

### ISSUE THREAD

**Issue by Lion4K** [rileytestut/AltStore#139] opened 2020-03-22 18:21 UTC
Is there any iOS minimum version to use altstore?

**Comment by noah978** [comment] 2020-05-24 04:54
I'm guessing this is probably a duplicate of #175. The minimum iOS version for AltStore is 12.2.

**Closed by noah978** 2020-05-24 04:54 UTC
Labels: duplicate
