### ISSUE TITLE
Unable to install 'AltStore' to iPhone Error : This action cannot be completed at this time (-22411)

### ISSUE THREAD

**Issue by djsmithuk** [rileytestut/AltStore#417] opened 2020-11-02 10:37 UTC
**Describe the bug**

**To Reproduce**
Update Mac to Mac OS Big Sur 11.0.1
Try to fresh install altstore with either a developer account or non developer account
You will receive different errors based on licensing

A developer account will go through the install process on the Mac, won't deploy the IPA to the phone and received and email from apple stating the iOS certificate has been revoked.

A non-dev account will give me the error : This action cannot be completed at this time (-22411) almost instantly

**Expected behavior**
Altstore gets deployed to iPhone

**Desktop (please complete the following information if applicable):**
 - OS: Mac
 - Version: BigSur

**iPhone (please complete the following information):**
 - Device: iPhone SE (2nd Gen)
 - iOS: 14.1

**Additional context and logs**
Add any error logs or any other context about the problem here.

**Comment by Spidy123222** [comment] 2020-11-05 07:51
This seems like a duplicate of #175

**Comment by djsmithuk** [comment] 2020-11-13 00:19
> This seems like a duplicate of #175
> 
> Edit: fix however is to you add the account into passwords&accounts and add the Apple ID where all the emails and stuff will be.

Sorry for the delayed reply, I went back to using the developer account and I identified the phone wouldn't display the apps on the springboard (but they were there) until a reboot - same applies when installing an IPA with AltStore from the phone itself.

**Closed** 2020-11-13 00:19 UTC
Labels: bug

**Comment by uysoft-en** [comment] 2022-06-24 12:53
It says "AltStore " cannot run on Devlopment
