### ISSUE TITLE
Invalid anisette data

### ISSUE THREAD

**Issue by azizo555** [rileytestut/AltStore#227] opened 2020-05-27 03:09 UTC
im trying to install altserver on my iphone 8 plus ios 13.5 on windows
but i keep getting this error Invalid anisette data close itunes and i cloud and try later 
please any help ?

**Comment by noah978** [comment] 2020-05-27 05:27
Duplicate of #156. Closing.

**Closed by noah978** 2020-05-27 05:27 UTC
Labels: duplicate

**Comment by lucidyan** [comment] 2020-05-27 21:19
For anyone who get `invalid anisette data close itunes and icloud` error on Windows, try to delete all files in this folder: `C:\ProgramData\Apple Computer\iTunes\adi`.

Source: official Altstore twitter
https://twitter.com/altstoreio/status/1264285607427104768
