### ISSUE TITLE
Won't fit iPad Screen

### ISSUE THREAD

**Issue by MyCatCondo** [rileytestut/AltStore#86] opened 2020-01-11 20:15 UTC
AltStore on iPad looks really small, and I wish it could actually fit the screen AKA a iPhone/iPad app. Could you please fix this?

**Comment by suyashbansal** [comment] 2020-01-14 12:31
Having the same issue. 😅

**Comment by JbAmade** [comment] 2020-02-29 12:00
There should be a double arrow at the bottom right to toggle from small to large view. It doesn’t fit iPad screen by default. The default view is for iPhone and it just makes it larger for iPad.

**Comment by Samuel12321** [comment] 2020-04-05 00:16
Suggest close superseded by #150

**Comment by noah978** [comment] 2020-05-22 04:27
This is a duplicate of #39. Closing this issue.

**Closed by noah978** 2020-05-22 04:27 UTC
Labels: duplicate
