### ISSUE TITLE
Altstore does not open

### ISSUE THREAD

**Issue by yun90s** [rileytestut/AltStore#657] opened 2021-01-30 14:49 UTC
https://user-images.githubusercontent.com/78266659/106359361-a1337f80-6312-11eb-929a-cf58921e6eb7.mov

**Comment by Tony-Sol** [comment] 2021-01-30 18:33
same

**Comment by osbre** [comment] 2021-01-30 20:05
Hello. I have the exact same problem. I installed it from **Big Sur**.

My IOS version: **14.3**
iPhone SE.

**Comment by GiovanH** [comment] 2021-01-30 21:17
Duplicate of https://github.com/rileytestut/AltStore/issues/652

**Comment by chichiwei** [comment] 2021-01-31 04:16
> Hello. I have the exact same problem. I installed it from **Big Sur**.
> 
> My IOS version: **14.3**
> iPhone SE.

same

**Comment by OdaFolx** [comment] 2021-01-31 11:27
This has been addressed on their Twitter ( https://twitter.com/altstoreio/status/1355273701068054532 ).

**Closed** 2021-05-25 22:36 UTC
