### ISSUE TITLE
Limit of 3 apps without having alstore installed 

### ISSUE THREAD

**Issue by yep123098** [rileytestut/AltStore#191] opened 2020-05-21 02:59 UTC
I haven’t got alstore on my device. I forgot to renew the certificate a couple of months back and wanted to get Spotify. I try to install it on my phone from alstore on windows and it says I’ve reached the limit of 3 apps on my device. I haven’t got the companion on my phone and haven’t got any profiles for any applications. I don’t know what to do and have asked around. No one has a solution yet.

**Comment by C0braD3v** [comment] 2020-05-21 05:22
To elaborate a bit: This user is using AltServer and the Patcher (For AppValley’s Companion Fork) however the issue persists without patching. It seems that even when using a different Apple ID, Altstore (or whatever patched IPA) will not install. This is caused by the “three active applications” restriction by Apple for these signing methods. It seems that the user has 3 applications installed on their device, so there is no room to sign (and Install) Altstore (or patched IPA) to the users device. Strangely enough, No applications are provisioned to the users device, and using a different Apple ID also did not allow the user further install Altstore/Patched IPA.

This is just some information I’ve gathered while supporting this user for AppValley’s Companion fork, and thought would be necessary in figuring out the necessary steps to mitigate the issue.

- Hunter, AppValley Community Management

**Comment by jamesmurdoch** [comment] 2020-05-21 14:46
I am having the same problem. I don't even have altstore on my device and it's saying the same thing as you.
![Screen Shot 2020-05-19 at 1 27 21 PM](https://user-images.githubusercontent.com/65624344/82570996-926bba80-9b3f-11ea-961a-662d54634776.png)

**Comment by C0braD3v** [comment] 2020-05-21 16:45
@jamesmurdoch You actually don't need it installed to get this error. Please make sure you have no provisioned apps on your device, i.e any sideloaded or tweaked apps signed to your personal dev cert. If you don't have any applications provisioned or signed, then it's most likely the same issue.

**Comment by noah978** [comment] 2020-05-21 23:24
This should be your solution: [https://twitter.com/altstoreio/status/1263608325465202688?s=20](@altstoreio Tweet)

It appears to an issue with iOS 13.5 where offloaded apps counts against your app and app extension count.

**Comment by noah978** [comment] 2020-05-22 00:22
Closing this issue since the solution has been found.

**Closed by noah978** 2020-05-22 00:22 UTC

**Comment by hbrtv** [comment] 2020-07-02 05:28
> To elaborate a bit: This user is using AltServer and the Patcher (For AppValley’s Companion Fork) however the issue persists without patching. It seems that even when using a different Apple ID, Altstore (or whatever patched IPA) will not install. This is caused by the “three active applications” restriction by Apple for these signing methods. It seems that the user has 3 applications installed on their device, so there is no room to sign (and Install) Altstore (or patched IPA) to the users device. Strangely enough, No applications are provisioned to the users device, and using a different Apple ID also did not allow the user further install Altstore/Patched IPA. The same issue was discussed on [this](https://mobile.twitter.com/BenjiDanecki/status/1255131984172482566) twitter thread in the Altstore Twitter, however I find it very strange that this user does not have any provisions to their device, since this is what would cause this error (having three provisions of apps on personal dev cert - sideloaded apps or tweaks).
> 
> This is just some information I’ve gathered while supporting this user for AppValley’s Companion fork, and thought would be necessary in figuring out the necessary steps to mitigate the issue.
> 
> ~ Hunter, AppValley Community Management

Yeah,I have met the same problem after I changed three iCloud ID when needed certificated by apple.I strongly believed that this problem is associated with the icloud ID account switching.I solve this problem by totally erase my iPhone

**Comment by QuarterSwede** [comment] 2022-12-07 21:27
I'm getting the same thing after Altstore expired. I'm running the beta of server on 1.6b4 and the solution suggested (since it's a lot more verbose now) was to deactivate an app (giving the 3 I have installed) but I can't do that if altstore won't install again.
