### ISSUE TITLE
this action could not be completed due to environmental mismatch -29004

### ISSUE THREAD

**Issue by AndrewXD2** [rileytestut/AltStore#181] opened 2020-05-03 18:10 UTC
this has been happening for several days now. every time i try updating altstore or refreshing my apps, i get that error code whenever i sign in. my apps have 1 day before they expire now and if this issue keeps happening, i can’t even use them. any fixes? i really need to know how to fix this. i want to keep using it, i’m on the same wifi as altserver and connected by wifi sync. i also tried plugging it into my PC and doing it by that way, but i get the same thing. i have no idea why. riley, please fix this. i’m on the altstore beta.

**Comment by noah978** [comment] 2020-05-22 22:27
Duplicate of #179. Closing this issue.

**Closed by noah978** 2020-05-22 22:27 UTC
Labels: duplicate
