### ISSUE TITLE
Failed to verify code signature (windows 10, latest version, iOS 13.4.1 iPhone 7 Plus)

### ISSUE THREAD

**Issue by marleyqp** [rileytestut/AltStore#168] opened 2020-04-23 10:14 UTC
This has never happened to me before. I tried going into ReProvision and revoking certificates but that didnt work either.

**Comment by noah978** [comment] 2020-05-22 22:50
Please try using the [latest version of AltServer](https://altstore.io/altserver/beta)

**Comment by noah978** [comment] 2020-05-24 21:08
Duplicate of #94. Closing this.

**Closed by noah978** 2020-05-24 21:08 UTC
Labels: duplicate

**Comment by imnisp** [comment] 2020-05-26 15:50
the problem (for some of us on windows 10) is that using the newest version of altstore generates:
"the procedure entry point IsWow64Process2 could not be located.."
