### ISSUE TITLE
AltStore app increases storage with every refresh

### ISSUE THREAD

**Issue by cry0sync** [rileytestut/AltStore#250] opened 2020-06-06 19:42 UTC
**Describe the bug**
Upon refreshing the AltStore app, it increases the Documents & Data storage usage, leading to a bloat in storage use by AltStore.  It seems the only way to clear that storage bloat is by uninstalling and reinstalling AltStore.

**To Reproduce**
1. Record current storage use by AltStore
2. Go to AltStore app
3. Click ‘Refresh All’ or just refresh AltStore
4. Wait a few moments, then go back to Settings to check storage use - Documents & Data by AltStore is increased.

**Expected behavior**
I expect little to no increase in storage use by AltStore after a refresh.

**Screenshots**
Before and after a refresh: ![image](https://user-images.githubusercontent.com/57244696/83953125-d501e800-a80b-11ea-8012-9f99e2a2880b.png)
![image](https://user-images.githubusercontent.com/57244696/83953127-d9c69c00-a80b-11ea-976f-f67975fcf66c.png)

**Desktop (please complete the following information if applicable):**
 - OS: Windows 10
 - Version: 2004 (although I originally noticed the bug on previous versions of Windows)

**iPhone (please complete the following information):**
 - Device: iPhone 7+
 - iOS: 13.5.1 (problem existed on previous versions too)

**Additional context and logs**
AltServer version: 1.3.2.0

In my previous installs of AltStore, the storage use has bloated up to 5gb before I reinstalled.  Other users have also experienced this bug and posted on reddit (https://reddit.com/r/AltStore/comments/gxr6o4/why_is_altstore_50_gb_the_only_app_i_am/), with AltStore using more than 50gb of storage.

Edit: forgot to mention, this bug does not seem to exist with Delta and sideloaded apps.

**Comment by noah978** [comment] 2020-06-07 04:02
Duplicate of #196, but thanks for all the additional data! This bug has been fixed before, but it keeps popping back up. For now, the only way to go back to normal storage quantities, you will need to delete AltStore.

**Closed by noah978** 2020-06-07 04:02 UTC
Labels: duplicate
