### ISSUE TITLE
Delta 1.2: NES roms loading to black screen

### ISSUE THREAD

**Issue by jsbobatea** [rileytestut/AltStore#426] opened 2020-11-07 07:59 UTC
**Describe the bug**
When loading any NES rom, it produces a black screen. I attempted to load one game from my save state (CV 2: SQ) and it loaded a black screen, with looping audio. 

**To Reproduce**
1. Download any legally owned NES game rom.
2. Import to Delta.
3. Load game, controller skin displays. 
4. Black screen, no gameplay or audio.

**Expected behavior**
When loading a NES rom, it should produce gameplay / audio. 

**iPhone (please complete the following information):**
 - Device: iPhone 11 Xs Max
 - iOS: 14.1

**Additional context and logs**
I verified it is not my install, as SNES / N64 / GBA / GB all load without issue. NES worked prior to downloading the newest update (Delta 1.2).

**Comment by shaunsingh** [comment] 2020-11-10 16:22
I can confirm, recently my nes rom (smb) is loading to a black screen as well. The rom is dumped and was working with the previous update

**Comment by ronaldsb** [comment] 2020-11-13 07:33
I have reported this bug many times.

https://www.dropbox.com/s/eydu5b4rfqiwq12/Delta%20bug%20with%20NES%20ROMS%20in%20iOS13.MP4?dl=0

https://www.dropbox.com/s/ke3uyxax131tnpq/Delta%20bug%20with%20NES%20ROMS%20in%20iOS14.MP4?dl=0

**Comment by ronaldsb** [comment] 2020-11-13 07:36
The bug was "fixed" only if you run first a Snes rom and then NES ROM. Or preview the game before running NES ROMS. I would love if this bug is fixed soon.

**Comment by jsbobatea** [comment] 2020-11-13 07:39
@ronaldsb Thanks for the workaround, can confirm it worked by loading SNES rom first, then NES. Very weird bug. Hopefully we see a fix. I may dig around and see if I can spot the cause myself.

**Comment by ronaldsb** [comment] 2020-11-13 07:40
Please please 🥺

**Comment by ronaldsb** [comment] 2020-11-13 07:45
Riley may know how to fix it because he just fixed in the last build the same build but only running first a Snes Rom. He just not fixed running only NES roms.

**Closed** 2021-01-05 17:56 UTC
Labels: bug
