### ISSUE TITLE
Failed to perform authentication handshake with server

### ISSUE THREAD

**Issue by jasons-open-repo** [rileytestut/AltStore#274] opened 2020-06-24 07:28 UTC
When I try to re-sign these three apps: AltStore Stable, Delta and Clips it shows this error:
(replication of the UI)
+
My Apps

| No Updates Available|

Active                          [Refresh All]

(icon) AltStore
          Riley Testut
(icon) Delta
          Riley Testut
(icon) Clips
          Riley Testut

         0 App IDs Remaining
               [View App IDs]
____________________________________________________________
| Failed to perform authentication handshake with server | 
|___________________________________________________________ |
News Brows (My Apps) Settings

Device Info: iPhone SE (2nd Generation) GSM Korean model iOS 14.0 Developer Beta 1
AltStore info: AltStore Version 1.3.4

Host (AltServer) info: MacBook Air Mid-2012 macOS Catalina 10.15.5 AltServer Version 1.3.4 (24)

Need more infos (Probably you don't)? DM me on my twitter. https://www.twitter.com/AltWeirdo

**Comment by ahsunchohan** [comment] 2020-06-24 07:49
Getting same on ios 14.0 beta (Iphone X)

**Comment by ygzok** [comment] 2020-06-24 08:03
Duplicate of #272

**Comment by jboothuk** [comment] 2020-06-25 21:58
I can confirm this bug also on IOS 14 beta 1

**Comment by rossvarrette** [comment] 2020-06-28 19:12
Same bug here. However, can get altserver to update by reinstalling from Mac.

**Comment by AppleWolfx** [comment] 2020-06-30 03:18
Bug

**Comment by AppleWolfx** [comment] 2020-06-30 03:19
I’m having the same issue as well hopefully they can release an update to fix for iOS 14 developer beta 1

**Comment by jasons-open-repo** [comment] 2020-07-02 17:30
Update: AltStore Beta version 1.4 fixes the handshake issue.

**Comment by fulloftsars** [comment] 2020-07-03 12:25
> Update: AltStore Beta version 1.4 fixes the handshake issue. 

It worked for me on Windows 10.

**Comment by HPaulson** [comment] 2020-07-08 13:12
This is a duplicate of #272 as mentioned previously. Please use that thread for this issue, since it's newer, and they are the exact same issue. More details on the iOS 14 branch & fix for this issue is available there - There's no value in having two duplicate issues for one problem.

**Comment by ajapk** [comment] 2020-07-29 23:48
This is still the issue on 13.1.2 on Windows

**Comment by noah978** [comment] 2020-07-31 01:59
Duplicate of #272. Closing this one, please continue any conversation there instead.

**Closed by noah978** 2020-07-31 01:59 UTC
Labels: bug
