### ISSUE TITLE
Instal problem 

### ISSUE THREAD

**Issue by zetroc95** [rileytestut/AltStore#138] opened 2020-03-21 21:10 UTC
![26DE270D-920C-4B3E-9225-879360B411D9](https://user-images.githubusercontent.com/62485146/77236627-996a6100-6bc0-11ea-82d4-1b1eb836bf8c.jpeg)
How can i resolve this problem?!
Please gelo me

**Comment by C0braD3v** [comment] 2020-04-03 15:43
This issue needs more info on what your issue is.

**Comment by noah978** [comment] 2020-05-24 04:58
Duplicate of #151. You can solve by disabling your firewall or creating an exception. Closing this issue.

**Closed by noah978** 2020-05-24 04:58 UTC
Labels: duplicate
