### ISSUE TITLE
MacOS 10.13.6 support?

### ISSUE THREAD

**Issue by Reiza1993** [rileytestut/AltStore#171] opened 2020-04-27 09:19 UTC
Why MacOS Hight Sierra 10.13.6 is not supported? I dont think is that old as MacOS.

**Comment by nikscave** [comment] 2020-05-01 21:06
i;ve tried changing the plist min support entry to 10.13.6 but that doesn't work.
please can you compile against an older version and release? thx

**Comment by noah978** [comment] 2020-05-22 04:58
Duplicate of #88. Closing this issue.

**Closed by noah978** 2020-05-22 04:58 UTC
